### ISSUE TITLE
Export SVGs and PNGs

### ISSUE THREAD

**Issue by remarkablemark** [remarkablemark/gdi-hack23-pathways-to-independence#2]
[Figma](https://www.figma.com/file/yNVq2asw1pZx0ZU7NONYwf/Pathway-to-Independence-Hack2023?type=whiteboard&node-id=278-970&t=zcAHHG8bz9ZMJsbs-0)

**Comment by DanielleLandry** [comment]
https://www.figma.com/file/GcZCUqRWhWtg2RJ3ftV5kG/Pathway-to-Independence-Hack2023?type=design&node-id=0%3A1&mode=design&t=8vVRw5S2LIDmhlhP-1

**Comment by remarkablemark** [comment]
![Enroll](https://github.com/remarkablemark/gdi-hack23-pathways-to-independence/assets/10594555/17d47266-a950-4aaa-91a6-662419aeea08)

![Profile picture](https://github.com/remarkablemark/gdi-hack23-pathways-to-independence/assets/10594555/82523d0c-26f7-4956-91b3-48ccf6866160)

**Comment by remarkablemark** [comment]
![Development](https://github.com/remarkablemark/gdi-hack23-pathways-to-independence/assets/10594555/96375cfe-49b9-47e7-8fb1-d6c683e553aa)
![Economics](https://github.com/remarkablemark/gdi-hack23-pathways-to-independence/assets/10594555/2d60fada-0996-4b8f-82ca-953eb8465add)
![Necessities](https://github.com/remarkablemark/gdi-hack23-pathways-to-independence/assets/10594555/7dcf8d7e-eec8-4724-bece-8c7d5556fc6c)
![Roadmap](https://github.com/remarkablemark/gdi-hack23-pathways-to-independence/assets/10594555/410df941-315d-41bf-8d3d-010e17ab2bca)
